from typing import List, Dict, Any

MOCK_POIS: List[Dict[str, Any]] = [
    {
        "id": 1,
        "name": "Hồ Hoàn Kiếm & Đền Ngọc Sơn",
        "category": "heritage",
        "description": "Trái tim của Thủ đô ngàn năm văn hiến, cầu Thê Húc đỏ son, Tháp Rùa cổ kính giữa lòng hồ xanh ngọc và truyền thuyết trả gươm thần.",
        "lat": 21.0287,
        "lon": 105.8523,
        "estimated_duration_min": 60,
        "opening_hours": "07:00 - 18:00",
        "ticket_price": 30000,
        "image_url": "/ho-hoan-kiem.jpg",
        "tips": "Nên đi bộ quanh bờ hồ lúc sáng sớm hoặc hoàng hôn. Vào cuối tuần có phố đi bộ với nhiều hoạt động nghệ thuật đường phố đặc sắc.",
        "ideal_time": "morning",
        "closed_days": [],
        "closed_time": "18:00"
    },
    {
        "id": 2,
        "name": "Lăng Chủ tịch Hồ Chí Minh & Ba Đình",
        "category": "heritage",
        "description": "Nơi an nghỉ của Chủ tịch Hồ Chí Minh vĩ đại, Quảng trường Ba Đình lịch sử, Nhà sàn, Phủ Chủ tịch và chùa Một Cột ngàn năm tuổi.",
        "lat": 21.0368,
        "lon": 105.8346,
        "estimated_duration_min": 120,
        "opening_hours": "07:30 - 11:00 (Đóng cửa thứ 2 & thứ 6)",
        "ticket_price": 0,
        "image_url": "/lang-bac.jpg",
        "tips": "Mặc trang phục lịch sự trang nghiêm (quần dài, áo có tay). Không mang theo máy quay phim hoặc đồ ăn uống vào trong lăng.",
        "ideal_time": "morning",
        "closed_days": [0, 4], # Thứ 2 & Thứ 6
        "closed_time": "11:00"
    },
    {
        "id": 3,
        "name": "Văn Miếu - Quốc Tử Giám",
        "category": "heritage",
        "description": "Trường đại học đầu tiên của Việt Nam với Khuê Văn Các biểu tượng, 82 tấm bia Tiến sĩ vinh danh truyền thống hiếu học ngàn năm.",
        "lat": 21.0293,
        "lon": 105.8359,
        "estimated_duration_min": 90,
        "opening_hours": "08:00 - 17:00",
        "ticket_price": 30000,
        "image_url": "/landing-bg.webp",
        "tips": "Nhiều góc chụp ảnh đẹp tại giếng Thiên Quang và cổng Đại Thành. Các sĩ tử thường đến xin chữ cầu may trước các kỳ thi quan trọng.",
        "ideal_time": "morning",
        "closed_days": [],
        "closed_time": "17:00"
    },
    {
        "id": 4,
        "name": "Khu Phố Cổ Hà Nội (36 Phố Phường)",
        "category": "culinary",
        "description": "Không gian phố nghề thủ công truyền thống rêu phong cổ kính cùng thiên đường ẩm thực: Phở Bát Đàn, bún chả Hàng Quạt, chả cá Lã Vọng.",
        "lat": 21.0366,
        "lon": 105.8500,
        "estimated_duration_min": 90,
        "opening_hours": "Cả ngày",
        "ticket_price": 0,
        "image_url": "/36-pho_phuong.jpg",
        "tips": "Nên trải nghiệm đi bộ hoặc xích lô luồn lách qua các ngõ nhỏ Hàng Mã, Hàng Ngang, Hàng Đào và thưởng thức cà phê trứng Giảng.",
        "ideal_time": "morning",
        "closed_days": [],
        "closed_time": None
    },
    {
        "id": 5,
        "name": "Hồ Tây & Chùa Trấn Quốc",
        "category": "nature",
        "description": "Hồ nước tự nhiên lớn nhất Thủ đô với chùa Trấn Quốc cổ kính hơn 1500 năm tuổi và không gian dã ngoại cúc họa mi sông Hồng thơ mộng.",
        "lat": 21.0545,
        "lon": 105.8285,
        "estimated_duration_min": 90,
        "opening_hours": "Cả ngày",
        "ticket_price": 0,
        "image_url": "/chua-tran-quoc.jpg",
        "tips": "Thời điểm ngắm hoàng hôn đẹp nhất Hà Nội là tại đường Thanh Niên hoặc bến Hàn Quốc. Thưởng thức bánh tôm Hồ Tây nóng giòn.",
        "ideal_time": "evening",
        "closed_days": [],
        "closed_time": None
    },
    {
        "id": 6,
        "name": "Hoàng thành Thăng Long",
        "category": "heritage",
        "description": "Di sản Văn hóa Thế giới UNESCO, trung tâm quyền lực chính trị qua 13 thế kỷ liên tục của các triều đại Lý, Trần, Lê, Mạc, Nguyễn.",
        "lat": 21.0353,
        "lon": 105.8402,
        "estimated_duration_min": 120,
        "opening_hours": "08:00 - 17:00",
        "ticket_price": 30000,
        "image_url": "/hoang-thanh.jpg",
        "tips": "Khu di tích khảo cổ 18 Hoàng Diệu rất rộng, hãy dành thời gian tham quan điện Kính Thiên và hầm chỉ huy D67 thời kháng chiến.",
        "ideal_time": "afternoon",
        "closed_days": [],
        "closed_time": "17:00"
    },
    {
        "id": 7,
        "name": "Bảo tàng Dân tộc học Việt Nam",
        "category": "museum",
        "description": "Bảo tàng hàng đầu trưng bày sống động về bản sắc văn hóa, y phục và kiến trúc nhà truyền thống thực địa của 54 dân tộc anh em.",
        "lat": 21.0406,
        "lon": 105.7984,
        "estimated_duration_min": 120,
        "opening_hours": "08:30 - 17:30 (Đóng cửa thứ 2)",
        "ticket_price": 40000,
        "image_url": "/bao_tang_dan_toc.webp",
        "tips": "Khu trưng bày ngoài trời có nhà rông Tây Nguyên, nhà sàn Ê Đê, nhà mồ Gia Rai rất ấn tượng, có múa rối nước vào cuối tuần.",
        "ideal_time": "afternoon",
        "closed_days": [0], # Thứ 2
        "closed_time": "17:30"
    },
    {
        "id": 8,
        "name": "Cầu Long Biên Lịch Sử",
        "category": "bridge",
        "description": "Cây cầu thép lịch sử hơn 120 năm bắc qua sông Hồng do hãng Daydé & Pillé thiết kế, chứng nhân lịch sử hào hùng của hai cuộc kháng chiến.",
        "lat": 21.0435,
        "lon": 105.8557,
        "estimated_duration_min": 45,
        "opening_hours": "Cả ngày",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=800&q=80",
        "tips": "Điểm chụp ảnh phong cách hoài cổ lý tưởng lúc bình minh hoặc hoàng hôn. Có thể thưởng thức ngô nướng, khoai nướng trên cầu vào mùa đông.",
        "ideal_time": "evening",
        "closed_days": [],
        "closed_time": None
    },
    {
        "id": 9,
        "name": "Nhà thờ Lớn Hà Nội (St. Joseph)",
        "category": "heritage",
        "description": "Kiệt tác kiến trúc Gothic phục hưng tuyệt đẹp thế kỷ 19 mô phỏng Nhà thờ Đức Bà Paris, trung tâm sinh hoạt Công giáo của Tổng giáo phận.",
        "lat": 21.0288,
        "lon": 105.8495,
        "estimated_duration_min": 45,
        "opening_hours": "08:00 - 20:00",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=800&q=80",
        "tips": "Trải nghiệm văn hóa 'trà chanh Nhà thờ' và nem chua rán vỉa hè số 10 Ấu Triệu ngay sát bên hông nhà thờ.",
        "ideal_time": "afternoon",
        "closed_days": [],
        "closed_time": "20:00"
    },
    {
        "id": 10,
        "name": "Di tích Lịch sử Nhà tù Hỏa Lò",
        "category": "museum",
        "description": "Di tích lịch sử cách mạng hào hùng với các tour trải nghiệm đêm 'Đêm thiêng liêng' xúc động, thu hút đông đảo du khách trong nước và quốc tế.",
        "lat": 21.0253,
        "lon": 105.8465,
        "estimated_duration_min": 90,
        "opening_hours": "08:00 - 17:00",
        "ticket_price": 30000,
        "image_url": "https://images.unsplash.com/photo-1578925518470-4def7a0f08bb?auto=format&fit=crop&w=800&q=80",
        "tips": "Nên thuê thiết bị thuyết minh tự động (audio guide) để nghe câu chuyện cảm động về ý chí kiên cường của các chiến sĩ cách mạng.",
        "ideal_time": "afternoon",
        "closed_days": [],
        "closed_time": "17:00"
    },
    {
        "id": 11,
        "name": "Nhà hát Lớn Hà Nội & Phố Tràng Tiền",
        "category": "heritage",
        "description": "Kiệt tác kiến trúc Tân cổ điển Pháp tại Quảng trường Cách Mạng Tháng Tám và trải nghiệm thưởng thức kem Tràng Tiền truyền thống.",
        "lat": 21.0242,
        "lon": 105.8576,
        "estimated_duration_min": 45,
        "opening_hours": "Cả ngày",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a1b?auto=format&fit=crop&w=800&q=80",
        "tips": "Địa điểm lý tưởng để chụp ảnh lưu niệm kiến trúc châu Âu giữa lòng Hà Nội và đi dạo mua sắm tại Tràng Tiền Plaza.",
        "ideal_time": "evening",
        "closed_days": [],
        "closed_time": None
    },
    {
        "id": 12,
        "name": "Chợ Đồng Xuân & Chợ Đêm Phố Cổ",
        "category": "culinary",
        "description": "Khu chợ đầu mối sầm uất bậc nhất Bắc Bộ với chợ đêm cuối tuần rực rỡ sắc màu quà lưu niệm, quần áo và đặc sản ẩm thực Hà thành.",
        "lat": 21.0382,
        "lon": 105.8498,
        "estimated_duration_min": 75,
        "opening_hours": "07:00 - 23:00 (Chợ đêm mở từ 18:00 thứ 6-CN)",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
        "tips": "Ngõ Đồng Xuân là thiên đường ăn vặt nức tiếng: bún ốc chuối đậu, chè sắn nóng, bánh tôm và phở tíu thơm lừng.",
        "ideal_time": "evening",
        "closed_days": [],
        "closed_time": "23:00"
    },
    {
        "id": 13,
        "name": "Bảo tàng Lịch sử Quân sự Việt Nam (Mới)",
        "category": "museum",
        "description": "Bảo tàng quân sự hiện đại bậc nhất quy mô 38.6ha lưu giữ 4 Bảo vật Quốc gia gồm máy bay MiG-21 số hiệu 4324, 5121 và xe tăng T-54B số hiệu 843.",
        "lat": 21.0118,
        "lon": 105.7483,
        "estimated_duration_min": 150,
        "opening_hours": "08:00 - 16:30 (Đóng cửa thứ 2 & thứ 6)",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
        "tips": "Khuôn viên rất rộng lớn bên cạnh đại lộ Thăng Long, trang bị công nghệ tương tác 3D mapping và sa bàn chiến dịch hiện đại.",
        "ideal_time": "morning",
        "closed_days": [0, 4], # Thứ 2 & Thứ 6
        "closed_time": "16:30"
    },
    {
        "id": 14,
        "name": "Công viên Nước Hồ Tây & Phố Trịnh Công Sơn",
        "category": "entertainment",
        "description": "Tổ hợp giải trí công viên nước sôi động cùng không gian phố đi bộ nghệ thuật ven hồ Tây lộng gió với nhiều quán cafe phong cách.",
        "lat": 21.0743,
        "lon": 105.8206,
        "estimated_duration_min": 150,
        "opening_hours": "08:30 - 19:00",
        "ticket_price": 180000,
        "image_url": "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80",
        "tips": "Thích hợp cho gia đình và nhóm bạn vui chơi giải nhiệt mùa hè, kết hợp ngắm sen Tây Hồ và thưởng thức ẩm thực sen độc đáo.",
        "ideal_time": "afternoon",
        "closed_days": [],
        "closed_time": "19:00"
    },
    {
        "id": 15,
        "name": "Làng Gốm Cổ Bát Tràng",
        "category": "entertainment",
        "description": "Làng nghề gốm sứ truyền thống hơn 700 năm bên bờ sông Hồng, trải nghiệm tự tay nặn gốm và chiêm ngưỡng Bảo tàng Gốm Bát Tràng 7 cánh xoáy ốc.",
        "lat": 20.9782,
        "lon": 105.9142,
        "estimated_duration_min": 180,
        "opening_hours": "08:00 - 18:00",
        "ticket_price": 50000,
        "image_url": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
        "tips": "Trung tâm Tinh hoa Làng nghề Việt (Bảo tàng gốm Bát Tràng) có kiến trúc 7 cánh xoáy tráng lệ, check-in sống ảo cực đẹp.",
        "ideal_time": "morning",
        "closed_days": [],
        "closed_time": "18:00"
    },
    {
        "id": 16,
        "name": "Lotte Mall West Lake Hanoi (Lotte Tây Hồ)",
        "category": "shopping",
        "description": "Đại siêu thị và tổ hợp mua sắm - giải trí phức hợp hiện đại bậc nhất Thủ đô rộng 354.000m² view Hồ Tây, quy tụ thủy cung Lotte World Aquarium và đại lộ thời trang quốc tế.",
        "lat": 21.0754,
        "lon": 105.8122,
        "estimated_duration_min": 120,
        "opening_hours": "09:30 - 22:00",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1519642918688-7e43b19245d8?auto=format&fit=crop&w=800&q=80",
        "tips": "Thủy cung trong nhà lớn nhất Hà Nội nằm tại tầng B1. Tầng 4 và 5 có hàng chục nhà hàng ẩm thực Á - Âu cùng ban công view hoàng hôn Hồ Tây cực chill.",
        "ideal_time": "afternoon",
        "closed_days": [],
        "closed_time": "22:00"
    },
    {
        "id": 17,
        "name": "Tràng Tiền Plaza & Phố Đi Bộ Hồ Gươm",
        "category": "shopping",
        "description": "Biểu tượng trung tâm thương mại xa xỉ và cổ kính bậc nhất Thủ đô từ năm 1901 thời Pháp thuộc, quy tụ các thương hiệu thời trang haute couture quốc tế (Dior, Louis Vuitton, Rolex) ngay sát Hồ Gươm.",
        "lat": 21.0258,
        "lon": 105.8546,
        "estimated_duration_min": 60,
        "opening_hours": "09:30 - 21:30",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=800&q=80",
        "tips": "Vị trí đắc địa ngay góc Tràng Tiền - Đinh Tiên Hoàng, cực kỳ thuận tiện kết hợp đi dạo phố đi bộ, chụp ảnh kiến trúc Pháp cổ và thưởng thức kem Tràng Tiền.",
        "ideal_time": "evening",
        "closed_days": [],
        "closed_time": "21:30"
    },
    {
        "id": 18,
        "name": "Vincom Mega Mall Times City & Thủy Cung",
        "category": "shopping",
        "description": "Đại trung tâm thương mại ngầm khổng lồ quy mô hàng chục nghìn mét vuông với thủy cung Vinpearl Aquarium đường hầm vòm kính sinh động, khu vui chơi VinKE và quảng trường nhạc nước.",
        "lat": 20.9950,
        "lon": 105.8677,
        "estimated_duration_min": 120,
        "opening_hours": "10:00 - 22:00",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=800&q=80",
        "tips": "Show nhạc nước miễn phí diễn ra lúc 19:00 hàng ngày tại hồ trung tâm. Thủy cung Vinpearl có hàng chục ngàn cá thể sinh vật biển quý hiếm.",
        "ideal_time": "evening",
        "closed_days": [],
        "closed_time": "22:00"
    },
    {
        "id": 19,
        "name": "Aeon Mall Long Biên",
        "category": "shopping",
        "description": "Đại siêu thị mua sắm và giải trí chuẩn phong cách Nhật Bản Omotenashi, khu ẩm thực đa dạng món ngon xứ sở hoa anh đào, rạp CGV lớn và bãi đỗ xe thênh thang miễn phí.",
        "lat": 21.0264,
        "lon": 105.9015,
        "estimated_duration_min": 120,
        "opening_hours": "10:00 - 22:00 (Cuối tuần từ 09:00)",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1581539250439-c96689b516dd?auto=format&fit=crop&w=800&q=80",
        "tips": "Khu Food Court tại tầng 1 và tầng 3 có bạt ngàn món sushi, sashimi, bánh bạch tuộc takoyaki ngon - bổ - rẻ.",
        "ideal_time": "afternoon",
        "closed_days": [],
        "closed_time": "22:00"
    },
    {
        "id": 20,
        "name": "Lotte Center Hà Nội (Liễu Giai) & Đài Quan Sát Sky Walk",
        "category": "shopping",
        "description": "Tòa tháp 65 tầng biểu tượng hiện đại với TTTM Lotte Department Store cao cấp, siêu thị Lotte Mart ngầm và đài quan sát sàn kính trong suốt Sky Walk ngắm trọn vẹn toàn cảnh Hà Nội từ độ cao 272m.",
        "lat": 21.0333,
        "lon": 105.8130,
        "estimated_duration_min": 90,
        "opening_hours": "09:30 - 22:00",
        "ticket_price": 0,
        "image_url": "https://images.unsplash.com/photo-1561069489-c5c56c21e3f8?auto=format&fit=crop&w=800&q=80",
        "tips": "Thời điểm lên đài quan sát Sky Walk tầng 65 đẹp nhất là lúc 17:30 ngắm hoàng hôn buông xuống thủ đô và thành phố lên đèn lung linh.",
        "ideal_time": "evening",
        "closed_days": [],
        "closed_time": "22:00"
    }
]
