import { POI } from '../types';

export const FALLBACK_POIS: POI[] = [
  { 
    id: 1, 
    name: 'Hồ Hoàn Kiếm & Đền Ngọc Sơn', 
    category: 'heritage', 
    lat: 21.0287, 
    lon: 105.8523, 
    estimated_duration_min: 60, 
    opening_hours: '07:00 - 18:00',
    ticket_price: 30000, 
    description: 'Trái tim của Thủ đô ngàn năm văn hiến, cầu Thê Húc đỏ son và Tháp Rùa cổ kính giữa lòng hồ xanh ngọc.',
    image_url: '/ho-hoan-kiem.jpg',
    tips: 'Nên đi bộ quanh bờ hồ lúc sáng sớm hoặc hoàng hôn. Vào cuối tuần có phố đi bộ với nhiều hoạt động nghệ thuật đường phố đặc sắc.',
    ideal_time: 'morning',
    closed_days: [],
    closed_time: '18:00',
    venue_type: 'outdoor'
  },
  { 
    id: 2, 
    name: 'Lăng Chủ tịch Hồ Chí Minh & Ba Đình', 
    category: 'heritage', 
    lat: 21.0368, 
    lon: 105.8346, 
    estimated_duration_min: 120, 
    opening_hours: '07:30 - 11:00 (Đóng cửa thứ 2 & thứ 6)',
    ticket_price: 0, 
    description: 'Quảng trường Ba Đình lịch sử, Lăng Bác và chùa Một Cột ngàn năm tuổi trang nghiêm.',
    image_url: '/lang-bac.jpg',
    tips: 'Mặc trang phục lịch sự trang nghiêm (quần dài, áo có tay). Không mang theo máy quay phim hoặc đồ ăn uống vào trong lăng.',
    ideal_time: 'morning',
    closed_days: [0, 4],
    closed_time: '11:00',
    venue_type: 'semi-indoor'
  },
  { 
    id: 3, 
    name: 'Văn Miếu - Quốc Tử Giám', 
    category: 'heritage', 
    lat: 21.0293, 
    lon: 105.8359, 
    estimated_duration_min: 90, 
    opening_hours: '08:00 - 17:00',
    ticket_price: 30000, 
    description: 'Trường đại học đầu tiên của Việt Nam với Khuê Văn Các biểu tượng hiếu học ngàn năm.',
    image_url: '/landing-bg.webp',
    tips: 'Nhiều góc chụp ảnh đẹp tại giếng Thiên Quang và cổng Đại Thành. Các sĩ tử thường đến xin chữ cầu may trước các kỳ thi quan trọng.',
    ideal_time: 'morning',
    closed_days: [],
    closed_time: '17:00',
    venue_type: 'semi-indoor'
  },
  { 
    id: 4, 
    name: 'Khu Phố Cổ Hà Nội (36 Phố Phường)', 
    category: 'culinary', 
    lat: 21.0366, 
    lon: 105.8500, 
    estimated_duration_min: 90, 
    opening_hours: 'Cả ngày',
    ticket_price: 0, 
    description: 'Mái ngói rêu phong và thiên đường ẩm thực phở, bún chả, cà phê trứng trứ danh.',
    image_url: '/36-pho_phuong.jpg',
    tips: 'Nên trải nghiệm đi bộ hoặc xích lô luồn lách qua các ngõ nhỏ Hàng Mã, Hàng Ngang, Hàng Đào và thưởng thức cà phê trứng Giảng.',
    ideal_time: 'morning',
    closed_days: [],
    venue_type: 'outdoor'
  },
  { 
    id: 5, 
    name: 'Hồ Tây & Chùa Trấn Quốc', 
    category: 'nature', 
    lat: 21.0545, 
    lon: 105.8285, 
    estimated_duration_min: 90, 
    opening_hours: 'Cả ngày',
    ticket_price: 0, 
    description: 'Hồ nước tự nhiên lộng gió và ngôi cổ tự nghìn năm trên đảo cá view hoàng hôn tuyệt mỹ.',
    image_url: '/chua-tran-quoc.jpg',
    tips: 'Thời điểm ngắm hoàng hôn đẹp nhất Hà Nội là tại đường Thanh Niên hoặc bến Hàn Quốc. Thưởng thức bánh tôm Hồ Tây nóng giòn.',
    ideal_time: 'evening',
    closed_days: [],
    venue_type: 'outdoor'
  },
  { 
    id: 6, 
    name: 'Hoàng thành Thăng Long', 
    category: 'heritage', 
    lat: 21.0353, 
    lon: 105.8402, 
    estimated_duration_min: 120, 
    opening_hours: '08:00 - 17:00',
    ticket_price: 30000, 
    description: 'Quần thể di sản văn hóa thế giới UNESCO nghìn năm lịch sử Thăng Long.',
    image_url: '/hoang-thanh.jpg',
    tips: 'Khu di tích khảo cổ 18 Hoàng Diệu rất rộng, hãy dành thời gian tham quan điện Kính Thiên và hầm chỉ huy D67 thời kháng chiến.',
    ideal_time: 'afternoon',
    closed_days: [],
    closed_time: '17:00',
    venue_type: 'semi-indoor'
  },
  { 
    id: 7, 
    name: 'Bảo tàng Dân tộc học Việt Nam', 
    category: 'museum', 
    lat: 21.0406, 
    lon: 105.7984, 
    estimated_duration_min: 120, 
    opening_hours: '08:30 - 17:30 (Đóng cửa thứ 2)',
    ticket_price: 40000, 
    description: 'Không gian văn hóa đặc sắc trong nhà và ngoài trời của 54 dân tộc anh em Việt Nam.',
    image_url: '/bao_tang_dan_toc.webp',
    tips: 'Khu trưng bày ngoài trời có nhà rông Tây Nguyên, nhà sàn Ê Đê, nhà mồ Gia Rai rất ấn tượng, có múa rối nước vào cuối tuần.',
    ideal_time: 'afternoon',
    closed_days: [0],
    closed_time: '17:30',
    venue_type: 'indoor'
  },
  {
    id: 8,
    name: 'Cầu Long Biên Lịch Sử',
    category: 'bridge',
    lat: 21.0435,
    lon: 105.8557,
    estimated_duration_min: 45,
    opening_hours: 'Cả ngày',
    ticket_price: 0,
    description: 'Cây cầu thép lịch sử hơn 120 năm bắc qua sông Hồng do hãng Daydé & Pillé thiết kế, chứng nhân lịch sử hào hùng.',
    image_url: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=800&q=80',
    tips: 'Điểm chụp ảnh phong cách hoài cổ lý tưởng lúc bình minh hoặc hoàng hôn. Có thể thưởng thức ngô nướng, khoai nướng trên cầu vào mùa đông.',
    ideal_time: 'evening',
    closed_days: [],
    venue_type: 'outdoor'
  },
  {
    id: 9,
    name: 'Nhà thờ Lớn Hà Nội (St. Joseph)',
    category: 'heritage',
    lat: 21.0288,
    lon: 105.8495,
    estimated_duration_min: 45,
    opening_hours: '08:00 - 20:00',
    ticket_price: 0,
    description: 'Kiệt tác kiến trúc Gothic phục hưng tuyệt đẹp thế kỷ 19 mô phỏng Nhà thờ Đức Bà Paris giữa lòng phố cổ.',
    image_url: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=800&q=80',
    tips: 'Trải nghiệm văn hóa trà chanh Nhà thờ và nem chua rán vỉa hè số 10 Ấu Triệu ngay sát bên hông nhà thờ.',
    ideal_time: 'afternoon',
    closed_days: [],
    closed_time: '20:00',
    venue_type: 'semi-indoor'
  },
  {
    id: 10,
    name: 'Di tích Lịch sử Nhà tù Hỏa Lò',
    category: 'museum',
    lat: 21.0253,
    lon: 105.8465,
    estimated_duration_min: 90,
    opening_hours: '08:00 - 17:00',
    ticket_price: 30000,
    description: 'Di tích lịch sử cách mạng hào hùng với các tour trải nghiệm đêm Đêm thiêng liêng xúc động và sâu lắng.',
    image_url: 'https://images.unsplash.com/photo-1578925518470-4def7a0f08bb?auto=format&fit=crop&w=800&q=80',
    tips: 'Nên thuê thiết bị thuyết minh tự động (audio guide) để nghe câu chuyện cảm động về ý chí kiên cường của các chiến sĩ cách mạng.',
    ideal_time: 'afternoon',
    closed_days: [],
    closed_time: '17:00',
    venue_type: 'indoor'
  },
  {
    id: 11,
    name: 'Nhà hát Lớn Hà Nội & Phố Tràng Tiền',
    category: 'heritage',
    lat: 21.0242,
    lon: 105.8576,
    estimated_duration_min: 45,
    opening_hours: 'Cả ngày',
    ticket_price: 0,
    description: 'Kiệt tác kiến trúc Tân cổ điển Pháp tại Quảng trường Cách Mạng Tháng Tám và trải nghiệm thưởng thức kem Tràng Tiền.',
    image_url: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a1b?auto=format&fit=crop&w=800&q=80',
    tips: 'Địa điểm lý tưởng để chụp ảnh lưu niệm kiến trúc châu Âu giữa lòng Hà Nội và đi dạo mua sắm tại Tràng Tiền Plaza.',
    ideal_time: 'evening',
    closed_days: [],
    venue_type: 'indoor'
  },
  {
    id: 12,
    name: 'Chợ Đồng Xuân & Chợ Đêm Phố Cổ',
    category: 'culinary',
    lat: 21.0382,
    lon: 105.8498,
    estimated_duration_min: 75,
    opening_hours: '07:00 - 23:00',
    ticket_price: 0,
    description: 'Khu chợ đầu mối sầm uất bậc nhất Bắc Bộ với chợ đêm cuối tuần rực rỡ sắc màu quà lưu niệm và đặc sản ẩm thực.',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    tips: 'Ngõ Đồng Xuân là thiên đường ăn vặt nức tiếng: bún ốc chuối đậu, chè sắn nóng, bánh tôm và phở tíu thơm lừng.',
    ideal_time: 'evening',
    closed_days: [],
    closed_time: '23:00',
    venue_type: 'semi-indoor'
  },
  {
    id: 13,
    name: 'Bảo tàng Lịch sử Quân sự Việt Nam (Mới)',
    category: 'museum',
    lat: 21.0118,
    lon: 105.7483,
    estimated_duration_min: 150,
    opening_hours: '08:00 - 16:30 (Đóng cửa thứ 2 & thứ 6)',
    ticket_price: 0,
    description: 'Bảo tàng quân sự hiện đại bậc nhất quy mô 38.6ha lưu giữ 4 Bảo vật Quốc gia gồm máy bay MiG-21 và xe tăng T-54B.',
    image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    tips: 'Khuôn viên rất rộng lớn bên cạnh đại lộ Thăng Long, trang bị công nghệ tương tác 3D mapping và sa bàn chiến dịch hiện đại.',
    ideal_time: 'morning',
    closed_days: [0, 4],
    closed_time: '16:30',
    venue_type: 'indoor'
  },
  {
    id: 14,
    name: 'Công viên Nước Hồ Tây & Phố Trịnh Công Sơn',
    category: 'entertainment',
    lat: 21.0743,
    lon: 105.8206,
    estimated_duration_min: 150,
    opening_hours: '08:30 - 19:00',
    ticket_price: 180000,
    description: 'Tổ hợp giải trí công viên nước sôi động cùng không gian phố đi bộ nghệ thuật ven hồ Tây lộng gió với nhiều quán cafe phong cách.',
    image_url: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80',
    tips: 'Thích hợp cho gia đình và nhóm bạn vui chơi giải nhiệt mùa hè, kết hợp ngắm sen Tây Hồ và thưởng thức ẩm thực sen độc đáo.',
    ideal_time: 'afternoon',
    closed_days: [],
    closed_time: '19:00',
    venue_type: 'outdoor'
  },
  {
    id: 15,
    name: 'Làng Gốm Cổ Bát Tràng',
    category: 'entertainment',
    lat: 20.9782,
    lon: 105.9142,
    estimated_duration_min: 180,
    opening_hours: '08:00 - 18:00',
    ticket_price: 50000,
    description: 'Làng nghề gốm sứ truyền thống hơn 700 năm bên bờ sông Hồng, tự tay nặn gốm và chiêm ngưỡng Bảo tàng Gốm 7 cánh xoáy.',
    image_url: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    tips: 'Trung tâm Tinh hoa Làng nghề Việt có kiến trúc 7 cánh xoáy tráng lệ, check-in sống ảo cực đẹp và có khu workshop nặn gốm.',
    ideal_time: 'morning',
    closed_days: [],
    closed_time: '18:00',
    venue_type: 'semi-indoor'
  },
  {
    id: 16,
    name: 'Lotte Mall West Lake Hanoi (Lotte Tây Hồ)',
    category: 'shopping',
    lat: 21.0754,
    lon: 105.8122,
    estimated_duration_min: 120,
    opening_hours: '09:30 - 22:00',
    ticket_price: 0,
    description: 'Đại siêu thị và tổ hợp mua sắm, thủy cung Lotte World Aquarium và đại lộ thời trang view Hồ Tây tuyệt đẹp.',
    image_url: 'https://images.unsplash.com/photo-1519642918688-7e43b19245d8?auto=format&fit=crop&w=800&q=80',
    tips: 'Thủy cung trong nhà lớn nhất Hà Nội nằm tại tầng B1. Tầng 4 và 5 có hàng chục nhà hàng ẩm thực Á - Âu cùng ban công view hoàng hôn.',
    ideal_time: 'afternoon',
    closed_days: [],
    closed_time: '22:00',
    venue_type: 'indoor'
  },
  {
    id: 17,
    name: 'Tràng Tiền Plaza & Phố Đi Bộ Hồ Gươm',
    category: 'shopping',
    lat: 21.0258,
    lon: 105.8546,
    estimated_duration_min: 60,
    opening_hours: '09:30 - 21:30',
    ticket_price: 0,
    description: 'Biểu tượng mua sắm xa xỉ và cổ kính nhất Thủ đô từ năm 1901 ngay sát bờ Hồ Gươm.',
    image_url: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=800&q=80',
    tips: 'Không gian máy lạnh mát mẻ, kiến trúc Pháp sang trọng, nơi hội tụ các thương hiệu thời trang quốc tế hàng đầu.',
    ideal_time: 'afternoon',
    closed_days: [],
    closed_time: '21:30',
    venue_type: 'indoor'
  },
  {
    id: 18,
    name: 'Vincom Mega Mall Times City & Thủy Cung',
    category: 'shopping',
    lat: 20.9950,
    lon: 105.8677,
    estimated_duration_min: 120,
    opening_hours: '09:30 - 22:00',
    ticket_price: 0,
    description: 'Đại TTTM ngầm khổng lồ với thủy cung Vinpearl Aquarium và quảng trường nhạc nước lung linh.',
    image_url: 'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=800&q=80',
    tips: 'Thủy cung Times City có đường hầm mái vòm 180 độ độc đáo và biểu diễn nàng tiên cá lúc 11:00 và 15:30 hàng ngày.',
    ideal_time: 'afternoon',
    closed_days: [],
    closed_time: '22:00',
    venue_type: 'indoor'
  },
  {
    id: 19,
    name: 'Aeon Mall Long Biên',
    category: 'shopping',
    lat: 21.0264,
    lon: 105.9015,
    estimated_duration_min: 120,
    opening_hours: '09:00 - 22:00',
    ticket_price: 0,
    description: 'Đại siêu thị mua sắm và ẩm thực chuẩn phong cách Nhật Bản Omotenashi rộng rãi, đầy đủ tiện nghi.',
    image_url: 'https://images.unsplash.com/photo-1581539250439-c96689b516dd?auto=format&fit=crop&w=800&q=80',
    tips: 'Khu ẩm thực tầng 1 và tầng 3 ngập tràn sushi, lẩu nướng, bánh ngọt Nhật Bản giá hợp lý, bãi gửi xe miễn phí khổng lồ.',
    ideal_time: 'afternoon',
    closed_days: [],
    closed_time: '22:00',
    venue_type: 'indoor'
  },
  {
    id: 20,
    name: 'Lotte Center Hà Nội (Liễu Giai) & Sky Walk',
    category: 'shopping',
    lat: 21.0333,
    lon: 105.8130,
    estimated_duration_min: 90,
    opening_hours: '09:00 - 23:00',
    ticket_price: 0,
    description: 'Tòa tháp 65 tầng biểu tượng với TTTM cao cấp và đài quan sát sàn kính Sky Walk tầng 65 nhìn bao trọn Hà Nội.',
    image_url: 'https://images.unsplash.com/photo-1561069489-c5c56c21e3f8?auto=format&fit=crop&w=800&q=80',
    tips: 'Vé lên đài quan sát tầng 65 cho trải nghiệm ngắm toàn cảnh Hà Nội từ trên mây và bước đi trên tấm kính trong suốt nghìn trượng.',
    ideal_time: 'evening',
    closed_days: [],
    closed_time: '23:00',
    venue_type: 'indoor'
  }
];
